receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  file/logs:
    path: /data/logs.jsonl
    format: json

  file/traces:
    path: /data/traces.jsonl
    format: json

  file/metrics:
    path: /data/metrics.jsonl
    format: json

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, file/logs]

    traces:
      receivers: [otlp]
      exporters: [debug, file/traces]

    metrics:
      receivers: [otlp]
      exporters: [debug, file/metrics]
